modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mystical"
version="1.0.0"
displayName="Mystical Creatures "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Steve, MCreator"

[[dependencies.mystical]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




